// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDoJWv3UQLTpAw0_2I3oDIfjwFX7-eoEmg',
    appId: '1:209051336023:web:8f7126f53245a7068b9212',
    messagingSenderId: '209051336023',
    projectId: 'sets-and-reps-2abf8',
    authDomain: 'sets-and-reps-2abf8.firebaseapp.com',
    storageBucket: 'sets-and-reps-2abf8.appspot.com',
    measurementId: 'G-T46JF2K3HS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA76Kr-bX1-Egj0NXumlToPntEtTrcrS3M',
    appId: '1:209051336023:android:85c52bc5f037c6e58b9212',
    messagingSenderId: '209051336023',
    projectId: 'sets-and-reps-2abf8',
    storageBucket: 'sets-and-reps-2abf8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhtv4oZ7aF_WwQdmsyu5if5gquYHu1sHc',
    appId: '1:209051336023:ios:27261e184e3d32878b9212',
    messagingSenderId: '209051336023',
    projectId: 'sets-and-reps-2abf8',
    storageBucket: 'sets-and-reps-2abf8.appspot.com',
    iosClientId: '209051336023-1g0rd11tb8qn23icvv5hfmv4sst4tupm.apps.googleusercontent.com',
    iosBundleId: 'com.example.gtkFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAhtv4oZ7aF_WwQdmsyu5if5gquYHu1sHc',
    appId: '1:209051336023:ios:27261e184e3d32878b9212',
    messagingSenderId: '209051336023',
    projectId: 'sets-and-reps-2abf8',
    storageBucket: 'sets-and-reps-2abf8.appspot.com',
    iosClientId: '209051336023-1g0rd11tb8qn23icvv5hfmv4sst4tupm.apps.googleusercontent.com',
    iosBundleId: 'com.example.gtkFlutter',
  );
}
